app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    # role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    pitches = db.relationship('Pitch',backref = 'user',lazy="dynamic")
    comments = db.relationship('Comment',backref = 'user', lazy="dynamic")
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    description_path = db.Column(db.String(255))
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    category = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    comments = db.relationship('Comment',backref = 'pitch',lazy="dynamic")
    def __repr__(self):
        return f'User {self.description_path}'
    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,id):
        pitches = Pitch.query.all()
        return pitches

    # @classmethod
    # def clear_pitches(cls):
    #    Pitch.all_pitches.clear()
    # users = db.relationship('User',backref = 'role',lazy="dynamic")

    

class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    description_all = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitches.id'))

    # users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f'Comment {self.description_all}'

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(id):
        comments = Comment.query.all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required
from wtforms.fields.html5 import DateField


class PitchForm(FlaskForm):
    category = StringField('Pitch category',validators=[Required()])
    description_path = TextAreaField('post a pitch')
    posted = DateField('date and time')

    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    description_all = TextAreaField('write a comment')
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'





# from .main import views
# from .main import error

bootstrap = Bootstrap()
db = SQLAlchemy()

photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()



def create_app(config_name):
    app = Flask(__name__)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
     
     
    # configure UploadSet
    # configure_uploads(app,photos)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

# Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    #  # Registering the blueprint
    
    # # setting config
    # from .request import configure_request
    # configure_request(app)


    return app

from .main import views
# from .main import error

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
# from . import views,error
from . import views

app/main/views.py
from flask_login import login_required,current_user
from . import main
from flask import render_template,request,redirect,url_for,abort
# from ..models import User,PhotoProfile
from ..models import User,Pitch,Comment
from .forms import UpdateProfile,PitchForm,CommentForm
# from .forms import ReviewForm,UpdateProfile
from .. import db,photos
import markdown2 



# @main.route('/movie/review/new/<int:id>', methods = ['GET','POST'])
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    pitches = Pitch.get_pitches(id)
    comments = Comment.get_comments()
    title = 'Home - Welcome to The best Pitches Review Website Online'

    return render_template('index.html', title = title, pitches=pitches,comments= comments)




@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


# @login_required
# def new_review(id):

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/pitch/new', methods = ['GET','POST'])
@login_required
def new_pitch():
    form = PitchForm()
    
    if form.validate_on_submit():
        # title = form.title.data
        description_path = form.description_path.data
        category = form.category.data
        posted = form.posted.data

        # Updated review instance
        new_pitch = Pitch(description_path=description_path, category=category,posted=posted, user_id= current_user.id)

        # save review method
        new_pitch.save_pitch()
        return redirect(url_for('.index',description_path = description_path ))

    # title = f'{movie.title} review'
    return render_template('new_pitch.html', pitch_form=form)





@main.route('/pitch/<int:id>')
def single_pitch(id):
    login_required
    pitch=Pitch.query.get(id)
    if pitch is None:
        abort(404)
    format_pitch = markdown2.markdown(pitch.user_pitch,extras=["code-friendly", "fenced-code-blocks"])
    return render_template('pitch.html',pitch = pitch,format_pitch=format_pitch)



@main.route('/pitch')
def diplay_pitch():
   pitches = Pitch.get_pitches()
   print(pitches)
   return render_template("new_pitch.html",pitches = pitches)


@main.route('/comment/new',methods= ['GET','POST'])
@login_required
def new_comment():
    form = CommentForm()
    if form.validate_on_submit():
        description_all = form.description_all.data
        
        

        # Updated review instance
        new_comment = Comment(description_all=description_all,user_id=current_user.id,)

        # save review method
        new_comment.save_comment()
        return redirect(url_for('.index',description_all=description_all ))

 
    return render_template('new_comment.html', comment_form=form)

@main.route('/comment',methods= ['GET','POST'])
@main.route('/comment')
def diplay_comment():
   comments = Comment.get_comments()
   print(comments)
   return render_template("comment.html",comments = comments)

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to the best Web application </title>
        {% endif %} 
        {% extends 'bootstrap/base.html'%}

        <!-- Navbar block  --> 
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock %}
    </head>
    <body>
        <!-- Content block -->

        {%block styles %}
        {{super()}}
        <!--Importing the simple mde css and js files  -->
        {{ simplemde.css}}
        {{ simplemde.js }}
      
      {% endblock %}  
        
    </body>
</html>

app/templates/comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block styles%}
        {{ super() }}
        <link rel="stylesheet" href="{{url_for('static',filename='index.css')}}">
        
        {% endblock %}
</head>
<body>
    {%block content%}
    {%for comment in comments%}
    <ul>
        <li>User:{{comment.user_id}}
        <li>Comment:{{comment.description_all}}</li>
        
       
    </ul>
    {%endfor%}
  
    {%endblock%}
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>

  <meta charset="UTF-8">
  {% if title %}

  <title> {{ title }}</title>
  {% else %}
  <title> Welcome to the best pitches </title>
  {% endif %}
  {% extends 'base.html'%}
  {% import 'macros.html' as macro%}
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block styles%}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}">
{% endblock %}
  
   
  </head>

<body>
 
  {% block content %}
  <div class="container-fluid">
  <h1 class="text-center text-lg">Hello wellcome to pitches</h1>
  </div>
  <blockquote class="text-center text-lg">

      {%for pitch in pitches%}       
     <p>Pitch:{{pitch.description_path}}</p> 
     

     <a href="/comment/new" class="btn btn-primary btn-md ">Leave comment</a>
     <a href="/comment" class="btn btn-primary btn-md ">view comments</a><br><br>
     <a href="" class="btn btn-primary btn-md">upvote</a>
     <a href="" class="btn btn-primary btn-md">downvote</a><br><br>
  
  {%endfor%}
  
  <a href="/pitch/new" class="btn btn-primary btn-md" >Add pitch</a>
  </blockquote>
  {% endblock%}
  </div>
</body>
</html>


 

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <!-- <span class="sr-only">Toggle navigation</span> -->
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h2 class="navbar-brand"> Web Application <h2>
      </div>
      <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}

             <!-- <li> <a class="navbar-brand" href="pitches">Pitches </a></li>
 
             <li> <a class="navbar-brand" href="{{url_for('main.new_pitch')}}">Add New Pitch</a></li> -->
              <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
              <li style="color:white;padding:15px;">{{current_user.username}}</li>
              <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
              {% else %}
              <li><a href="{{url_for('auth.login')}}">login</a></li>
              {%endif%}
          </ul>
      </div>

  </div>
</div>

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%}
        {{ super() }}
        <link rel="stylesheet" href="{{url_for('static',filename='index.css')}}">
    
        {% endblock %}
{% block content %}
    <div class="container">

      

        

            {{ wtf.quick_form(comment_form) }}
        </div>
       

    {%endblock%}

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%}
        {{ super() }}
        <link rel="stylesheet" href="{{url_for('static',filename='index.css')}}">
              {% endblock %}
{% block content %}
    <div class="container">

      

        

            {{ wtf.quick_form(pitch_form) }}
        </div>

   

    {%endblock%}

app/templates/pitch.html
{% extends 'base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block styles%}
        {{ super() }}
        <link rel="stylesheet" href="{{url_for('static',filename='index.css')}}">
        <link href="https://fonts.googleapis.com/css?family=Laila" rel="stylesheet">
        {% endblock %}
</head>
<body>
  {%block content%}
  {% for pitch in pitches%}

  <ul>
    <li>{{pitch.description_path}}</li>
  <ul>

  {%endfor%}
  {%endblock%}

</body>
</html>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}

    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
      <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
     
      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}

      

</div>
</div>
{% endblock %}

app/templates/profile/update.html
% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}